### ISSUE TITLE
NodeMCU board led blinking

### ISSUE THREAD

**Issue by cryptooth** [andrei7c4/espspotifydisplay#1]
Hello,

Thank you for this great project. I have flashed NodeMCU like esptwitterclient project.
But after all tree comands (make all, make flashall and make flash) (second one takes time) flashing completed. When I reboot the NodeMCU, blue led continously flashing and there is no sign on display.

Is there any trick?

Thank you.

**Comment by andrei7c4** [comment]
Hi,
Do you also have buttons wired? Or at least pull-up resistor at AD0 pin? If no, then weird things can happen because the code would think that buttons are continuously triggered. You can either wire the buttons or disable buttons scanning in the code by commenting out this line in main.c file:
os_timer_arm(&buttonsTmr, 100, 1);

**Comment by cryptooth** [comment]
I tried both. Nothing changed. When I try to get serial monitor with Arduino IDE on my mac, I see random characters.

**Comment by andrei7c4** [comment]
Try the following:
- in config.c file, configInit function set config->debugEn = TRUE;
- set your WiFi SSID and password in config.h file
- change VALID_MAGIC_NUMBER to something else
- rebuild and reflash
- check what is printed to the serial port (baud rate is 921600)

**Comment by cryptooth** [comment]
Here is my serial print
```

2dO,4?h?4?H<
             $$8?y|l?$<p?\?
                           ?HQȰ?`dC]?p >?,?H<`dOM?p`:?^4?txG?????x?E?d?lb<l,?xO?X??2dn,??hdY?$?YIH:?xɨXl?$?p?|??H??`dCM?p >?,?H<`dOM?p`:?4l??
                                                                                                                                             txG??$??x?U?l <?,?:?0츴$n?+?H???4C,$d?x?U?]?4C(}?$l???h?Y?h?YIi<?x?EXҴh?p?\Ս?HP??? db]?p$>d??$?`dnM?x?:?0l???l <?$?@>?t??l`8?4l??
                                                                                            txW??$??z?U?l <CY??l`<l$?@>?t??l`8?0l??
                                                                                                                                   txW?????xɨXҴlb<l,?xX??0dn,??h?Y?$?YII<?x?EXҴh?p?^?H?l?`dC]?p >?,?H<`dOM?p`:?0l??????l??D:?t?
                                             ?p$>x?D:n?P??Ȥl???H???4C$d?x?U?]?4C(^??HpY??$ |?y6???4C,$l?y2?X??2dn,??hdY?$?YIH:?xɨXl?$?p?\Ս?Hp?4?bDCM?l >C/Y?@>?t?M??`:?4l??
                                                        
```

**Comment by andrei7c4** [comment]
Sorry, but I ran out of ideas. Your ESP8266 does not seem to be booting properly for some reason, I don't really know why or how to debug it further.

**Comment by cryptooth** [comment]
I'm using ubuntu 14.04 and esp-open-sdk installed.

When I run the make all command. Operation finished like below:

`Section info:

build/app.out:     file format elf32-xtensa-le

Sections:
Idx Name          Size      VMA       LMA       File off  Algn
  0 .data         000008e8  3ffe8000  3ffe8000  00000100  2**4
                  CONTENTS, ALLOC, LOAD, DATA
  1 .rodata       000016f0  3ffe88f0  3ffe88f0  000009f0  2**4
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
  2 .bss          00009bf0  3ffe9fe0  3ffe9fe0  000020e0  2**4
                  ALLOC
  3 .text         00007df0  40100000  40100000  000020e0  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, CODE
  4 .irom0.text   0003f4dc  40210000  40210000  00009ed0  2**4
                  CONTENTS, ALLOC, LOAD, READONLY, CODE
  5 .font0.text   003609e4  4025b000  4025b000  000493ac  2**2
                  CONTENTS, ALLOC, LOAD, READONLY, DATA
------------------------------------------------------------------------------
esptool.py v1.2
   Section|                   Description| Start (hex)|   End (hex)|Used space
------------------------------------------------------------------------------
      data|        Initialized Data (RAM)|    3FFE8000|    3FFE88E8|    2280
    rodata|           ReadOnly Data (RAM)|    3FFE88F0|    3FFE9FE0|    5872
       bss|      Uninitialized Data (RAM)|    3FFE9FE0|    3FFF3BD0|   39920
      lit4|     Uninitialized Data (IRAM)|    40107DF0|    40107DF0|       0
      text|          Uncached Code (IRAM)|    40100000|    40107DF0|   32240
irom0_text|             Cached Code (SPI)|    40210000|    4024F4DC|  259292
font0_text|               Font data (SPI)|    4025B000|    405BB9E4| 3541476
------------------------------------------------------------------------------
Total Used RAM : 80312
Free IRam : 528
Free Heap : 33848
Total Free RAM : 50760
`
After running "make flashall" result like this:

`root@ubuntu:/home/kayhan/espspotifydisplay# make flashall
tools/esptool.py -p /dev/ttyUSB0 -b 115200 write_flash -ff 40m -fm dio -fs 32m 0x00000 firmware/0x00000.bin 0x10000 firmware/0x10000.bin 0x5b000 firmware/0x5b000.bin
esptool.py v1.2
Connecting...
Running Cesanta flasher stub...
Flash params set to 0x0240
Writing 40960 @ 0x0... 40960 (100 %)
Wrote 40960 bytes at 0x0 in 3.6 seconds (92.0 kbit/s)...
Writing 262144 @ 0x10000... 262144 (100 %)
Wrote 262144 bytes at 0x10000 in 22.7 seconds (92.3 kbit/s)...
Writing 3543040 @ 0x5b000... 3543040 (100 %)
Wrote 3543040 bytes at 0x5b000 in 307.1 seconds (92.3 kbit/s)...
Leaving...
root@ubuntu:/home/kayhan/espspotifydisplay# `

After that, I'm unplug and replug power to ESP module, blue led continously flashing.  (tried 2 nodeMCU modules)

**Comment by cryptooth** [comment]
Could there be a problem with ttyUSB0 baudrate?

**Comment by andrei7c4** [comment]
This is very much possible. Try to change baud rate to 115200 in user_init function in main.c.

**Comment by cryptooth** [comment]
woohooo. Flashed and booted. But I'm gettin an message from serial monitor when I push the button:

`please start sntp first !`

**Comment by andrei7c4** [comment]
Does it connect successfully to your WiFi? If yes, then proceed to setting Spotify parameters as described in readme.

**Comment by cryptooth** [comment]
Where do I write the auth_code (Spotify app authorization code)? I didnt find in config.h

**Comment by cryptooth** [comment]
and we have new issue :)
can't connect to WiFi. SSID and password correct in config file. 
```
rm 0
reconnect
state: 2 -> 0 (0)
scandone
state: 0 -> 2 (b0)
state: 2 -> 3 (0)
state: 3 -> 5 (10)
add 0
aid 6
cnt 
state: 5 -> 2 (2c0)

```

**Comment by andrei7c4** [comment]
Remember that each time you change settings by editing config.h, you also need to change VALID_MAGIC_NUMBER to something else. Now when you have serial interface working, it is easier to use it for changing settings. The syntax is:
parameter:value<carriage_return>

It is also the only way to set authorization code, e.g.:
auth_code:your_auth_code_here<carriage_return>

**Comment by cryptooth** [comment]
and here is the last status:

```
POST /api/token HTTP/1.1
Accept: */*
Connection: keep-alive
User-Agent: ESP8266
Content-Type: application/x-www-form-urlencoded
Authorization: Basic XXXXXXXXXXXXXXXXXlYTljOTc1MjljNTNiY2QxYTg6ZWM0YWRkYjY0Yjg5NGNhMWI0NGU2YWE5YzY4Mjc5YTU=
Content-Length: 39
Host: accounts.spotify.com

grant_type=refresh_token&refresh_token=

appState 4
onTcpDataSent
onTcpDataRecv 339
appState 5
parseAuthReply, len 339
parseTokens failed
HTTP/1.1 400 Bad Request
Server: nginx
Date: Fri, 15 Dec 2017 10:31:40 GMT
Content-Type: application/json
Content-Length: 80
Connection: keep-alive
Keep-Alive: timeout=600
X-Content-Type-Options: nosniff
Strict-Transport-Security: max-age=31536000

{"error":"invalid_request","error_description":"refresh_token must be supplied"}
client's data invalid protocol
Error: SSL error 3
onTcpDisconnected
disconnExpected 0
reconnCbCalled 0

```

**Comment by andrei7c4** [comment]
At which situation you get this? After entering authorization code it should start polling for the currently playing track. Do you see it doing so?

**Comment by cryptooth** [comment]
1- Power on ESP Module
2- Play a track on spotify
3- copy/paste auth_code:XXXXXXXXXXXX to serial monitor and hit send
4- auth_code:XXXXXX displaying in serial monitor with "pm open, type:2 0"
5- Only Spotify Logo displayed on OLED
6- When I click to switch (A0+GND)
7- getting this error codes

**Comment by andrei7c4** [comment]
Do you see 'OK' printed after you enter the auth. code? If no, then your terminal is not sending carriage return at the end. Also, remember that the auth. code is valid for a few minutes only, so you need to enter it right after you get it from Spotify server.

**Comment by cryptooth** [comment]
Woohooo! It's work!!!! There are too many tricks. Thank for your efforts... ^_^

**Comment by andrei7c4** [comment]
No problem, I am glad you made it work :)
