### ISSUE TITLE
Recurrent parseTrackInfo error

### ISSUE THREAD

**Issue by slash4** [andrei7c4/espspotifydisplay#5]
Hi and thanks for sharing this very cool and inspiring piece of software ! I achieved some pretty good results but pretty often, this happens :

The program retry to connect, sometimes 3 of 4 times in a row and then reconnects. And falls down again few seconds later.   Any insights on what may happen ?

Rgds, Alex

**Comment by slash4** [comment]
> appState 4
onTcpDataSent
onTcpDataRecv 1373
onTcpDataRecv 1373
client's data invalid protocol
Error: invalid mac
onTcpReconnCb
appState 5
parseApiReply, len 2746
parseTrack failed (0x10)
nextPoll after 3 s
heap: 28600
appState 2
reconnect
espconn_secure_connect 0
client handshake start.
reconnect
espconn_secure_connect -1
onTcpDisconnected
disconnExpected 0
reconnCbCalled 1

**Comment by slash4** [comment]
I noticed that it fails every time we have only 2 `onTcpDataRecv 1373` sentences, followed by `parseApiReply, len 2746`. The "invalid mac" sentence is not present every time. It really makes me think of a parsing issue. An intermittent one...

I compensated this problem by calling more frequently (every 3 seconds), but I would prefer understand what's happening and lower this rate. I have 2 ideas : 
- Maybe spotify limits us without telling us, or serves an incomplete json at certain moments
- Maybe something is moving into the json and sometimes cannot be parsed correctly

I'm investigating but a quick glance from the creator himself cannot harm :)

**Comment by slash4** [comment]
I tried to manually call the spotify api with postman, and I see no noticeable differences between my calls, even at a very high rate. Just the "elapsed time" of current track moves, which is... normal :) 

So I wonder if we are not facing a resource management issue, like all the memory isn't freed each time the json parsing finishes. I'm still investigating, but I have very few spare time to invest into this, so it may take some time !!

**Comment by andrei7c4** [comment]
It is the issue with ESP8266 SDK: https://bbs.espressif.com/viewtopic.php?f=7&t=1989
I guess it runs out of memory when using secure TCP. It has nothing to do with Spotify. The same happens with Twitter and other services. I don't think it can be fixed on ESP8266. Maybe ESP32 is better, but I have not tried it.

**Comment by slash4** [comment]
Wow, thanks for pointing this out ! I was clearly searching in the wrong direction. I guess I can close the issue for now. I'll try with an ESP32. Let's hope code can be converted without too much problems.

**Comment by slash4** [comment]
Just received my ESP32, I'm going to update esptool.py and Makefile with these : 

New makefile : https://github.com/CHERTS/esp32-devkit/blob/master/Espressif/examples/ESP32/esp32_hello_world/Makefile
New esptool.py : https://github.com/espressif/esptool/blob/master/esptool.py

This should allow ESP32 compilation and flashing. Next step : figure out what needs to be changed in the actual source. If you have any insight I'm interested :)
